//
//  AppDelegate.swift
//  WeatherApp
//
//  Created by Khue on 04/08/2022.
//

import UIKit

@main
class AppDelegate: UIResponder, UIApplicationDelegate {

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
//        addCountryDatabase()
        print(FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first)
        return true
    }

    // MARK: UISceneSession Lifecycle

    func application(_ application: UIApplication, configurationForConnecting connectingSceneSession: UISceneSession, options: UIScene.ConnectionOptions) -> UISceneConfiguration {
        // Called when a new scene session is being created.
        // Use this method to select a configuration to create the new scene with.
        return UISceneConfiguration(name: "Default Configuration", sessionRole: connectingSceneSession.role)
    }

    func application(_ application: UIApplication, didDiscardSceneSessions sceneSessions: Set<UISceneSession>) {
        // Called when the user discards a scene session.
        // If any sessions were discarded while the application was not running, this will be called shortly after application:didFinishLaunchingWithOptions.
        // Use this method to release any resources that were specific to the discarded scenes, as they will not return.
    }

    func addCountryDatabase(){
        let queries = """
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (1,"Afghanistan",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (2,"Albania",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (3,"Algeria",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (4,"Andorra",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (5,"Angola",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (6,"Antigua and Barbuda",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (7,"Argentina",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (8,"Armenia",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (9,"Australia",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (10,"Austria",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (11,"Azerbaijan",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (12,"Bahamas",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (13,"Bahrain",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (14,"Bangladesh",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (15,"Barbados",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (16,"Belarus",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (17,"Belgium",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (18,"Belize",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (19,"Benin",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (20,"Bhutan",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (21,"Bolivia",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (22,"Bosnia and Herzegovina",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (23,"Botswana",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (24,"Brazil",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (25,"Brunei",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (26,"Bulgaria",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (27,"Burkina Faso",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (28,"Burundi",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (29,"Côte d'Ivoire",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (30,"Cabo Verde",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (31,"Cambodia",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (32,"Cameroon",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (33,"Canada",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (34,"Central African Republic",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (35,"Chad",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (36,"Chile",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (37,"China",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (38,"Colombia",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (39,"Comoros",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (40,"Congo (Congo-Brazzaville)",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (41,"Costa Rica",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (42,"Croatia",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (43,"Cuba",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (44,"Cyprus",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (45,"Czechia (Czech Republic)",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (46,"Democratic Republic of the Congo",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (47,"Denmark",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (48,"Djibouti",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (49,"Dominica",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (50,"Dominican Republic",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (51,"Ecuador",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (52,"Egypt",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (53,"El Salvador",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (54,"Equatorial Guinea",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (55,"Eritrea",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (56,"Estonia",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (57,"Eswatini (fmr. Swaziland)",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (58,"Ethiopia",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (59,"Fiji",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (60,"Finland",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (61,"France",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (62,"Gabon",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (63,"Gambia",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (64,"Georgia",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (65,"Germany",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (66,"Ghana",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (67,"Greece",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (68,"Grenada",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (69,"Guatemala",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (70,"Guinea",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (71,"Guinea-Bissau",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (72,"Guyana",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (73,"Haiti",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (74,"Holy See",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (75,"Honduras",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (76,"Hungary",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (77,"Iceland",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (78,"India",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (79,"Indonesia",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (80,"Iran",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (81,"Iraq",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (82,"Ireland",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (83,"Israel",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (84,"Italy",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (85,"Jamaica",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (86,"Japan",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (87,"Jordan",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (88,"Kazakhstan",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (89,"Kenya",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (90,"Kiribati",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (91,"Kuwait",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (92,"Kyrgyzstan",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (93,"Laos",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (94,"Latvia",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (95,"Lebanon",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (96,"Lesotho",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (97,"Liberia",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (98,"Libya",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (99,"Liechtenstein",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (100,"Lithuania",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (101,"Luxembourg",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (102,"Madagascar",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (103,"Malawi",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (104,"Malaysia",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (105,"Maldives",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (106,"Mali",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (107,"Malta",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (108,"Marshall Islands",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (109,"Mauritania",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (110,"Mauritius",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (111,"Mexico",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (112,"Micronesia",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (113,"Moldova",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (114,"Monaco",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (115,"Mongolia",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (116,"Montenegro",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (117,"Morocco",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (118,"Mozambique",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (119,"Myanmar (formerly Burma)",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (120,"Namibia",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (121,"Nauru",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (122,"Nepal",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (123,"Netherlands",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (124,"New Zealand",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (125,"Nicaragua",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (126,"Niger",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (127,"Nigeria",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (128,"North Korea",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (129,"North Macedonia",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (130,"Norway",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (131,"Oman",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (132,"Pakistan",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (133,"Palau",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (134,"Palestine State",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (135,"Panama",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (136,"Papua New Guinea",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (137,"Paraguay",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (138,"Peru",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (139,"Philippines",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (140,"Poland",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (141,"Portugal",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (142,"Qatar",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (143,"Romania",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (144,"Russia",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (145,"Rwanda",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (146,"Saint Kitts and Nevis",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (147,"Saint Lucia",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (148,"Saint Vincent and the Grenadines",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (149,"Samoa",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (150,"San Marino",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (151,"Sao Tome and Principe",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (152,"Saudi Arabia",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (153,"Senegal",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (154,"Serbia",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (155,"Seychelles",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (156,"Sierra Leone",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (157,"Singapore",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (158,"Slovakia",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (159,"Slovenia",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (160,"Solomon Islands",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (161,"Somalia",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (162,"South Africa",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (163,"South Korea",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (164,"South Sudan",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (165,"Spain",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (166,"Sri Lanka",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (167,"Sudan",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (168,"Suriname",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (169,"Sweden",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (170,"Switzerland",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (171,"Syria",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (172,"Tajikistan",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (173,"Tanzania",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (174,"Thailand",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (175,"Timor-Leste",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (176,"Togo",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (177,"Tonga",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (178,"Trinidad and Tobago",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (179,"Tunisia",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (180,"Turkey",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (181,"Turkmenistan",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (182,"Tuvalu",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (183,"Uganda",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (184,"Ukraine",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (185,"United Arab Emirates",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (186,"United Kingdom",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (187,"United States of America",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (188,"Uruguay",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (189,"Uzbekistan",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (190,"Vanuatu",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (191,"Venezuela",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (192,"Vietnam",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (193,"Yemen",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (194,"Zambia",0)
                INSERT INTO COUNTRY(id,name,ischeck) VALUES (195,"Zimbabwe",0)
        """.components(separatedBy: .newlines)
        
        for query in queries {
            DBController.shared.executeUpdate(query: query)
        }
    }
}

